#Configuration file for inverse_kinematics_node
inverse_kinematics:
  ros__parameters:
      base_id: 1 #motive ID of the robot base
      ring_ids: [3, 4] #motive IDs of the rings of each segment, ordered from the robot base to te tip
      ring_ls: [0.1015, 0.1015] #distance at rest of each ring from the base of the corresponding segment, ordered from robot base to the tip
      ring_ds: [0.022, 0.022] #diameter of each segment, ordered from the robot base to the tip
      segment_ls: [0.11, 0.11] #length of each segment, ordered from the robot base to the tip
      sub_topic: "rigid_body_baseframe_topic" 
      pub_topic: "configuration_topic" #topic where the configuration vector of the robot is published