#Configuration file for the world_to_base node (w2b)
world_to_base:
  ros__parameters:
      #Orientation of the robot base w.r.t. Motive Frame as unit quaternion
      base_qx: -0.7071068 
      base_qy: 0.0
      base_qz: 0.0
      base_qw: 0.7071068
      initial_offset_x: 0.0
      initial_offset_y: -0.019 #unit of measures are in [m]
      initial_offset_z: 0.0
      base_id: 1 #motive ID of the robot base
      sub_topic: "rigid_body_topic"
      pub_topic: "rigid_body_baseframe_topic"